# Generated by Django 3.1.4 on 2021-01-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='liked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='loved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='love',
            field=models.IntegerField(default=0),
        ),
    ]
