# Generated by Django 3.1.4 on 2021-01-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210104_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='name',
        ),
        migrations.AddField(
            model_name='basket',
            name='category',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='basket',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
