# Generated by Django 3.1.4 on 2021-01-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.TextField(default='')),
                ('category', models.TextField(default='')),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Love',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.TextField(default='')),
                ('category', models.TextField(default='')),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
