# Generated by Django 3.1.4 on 2021-01-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210106_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='customer_id',
            field=models.TextField(default=''),
        ),
    ]
