# Generated by Django 3.1.5 on 2021-01-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_orderlist_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.TextField()),
                ('title', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
